#!/bin/bash

if [[ "$OSTYPE" == "darwin" ]]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
fi

git clone --recursive git@github.com:sysbot/dotfiles "$HOME/dotfiles"

brew install git chruby hub
